definitions:
  auth.LoginData:
    properties:
      name:
        type: string
      password:
        type: string
      verify:
        type: string
    type: object
  http.HttpResult:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  models.User:
    properties:
      affiliation:
        description: 工作单位
        type: string
      create_time:
        description: 创建时间
        type: string
      display_name:
        description: 显示名称
        type: string
      email:
        description: 邮箱地址
        type: string
      handle_user_name:
        description: 上次操作用户
        type: string
      id:
        description: ID创建时不用传
        type: integer
      mobile:
        description: 手机号
        type: string
      name:
        description: 用户名
        type: string
      organization:
        description: 工作组织
        type: string
      password:
        description: 用户密码不更新密码不用填
        type: string
      position:
        description: 职位
        type: string
      super_admin:
        description: 是否是超级用户
        type: boolean
      update_time:
        description: 更新时间
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/login/local:
    post:
      description: 本地用户登录
      parameters:
      - description: 登录信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.LoginData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.HttpResult'
      summary: 本地用户登录
      tags:
      - 登录相关接口
  /v1/logout:
    get:
      description: 登出
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.HttpResult'
      summary: 登出
      tags:
      - 登录相关接口
  /v1/user:
    delete:
      description: 删除user
      parameters:
      - description: 多个ID 每个ID之间用,分隔，例：123,233
        in: query
        items:
          type: integer
        name: ids
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.HttpResult'
      summary: 删除user
      tags:
      - 用户相关接口
    get:
      description: 搜索用户
      parameters:
      - description: 过滤关键词
        in: query
        name: filter
        type: string
      - description: 多个ID 每个ID之间用,分隔，例：123,233 注：跟 name 参数只有一个会生效，hostids参数优先级
        in: query
        items:
          type: integer
        name: pageNo
        type: array
      - description: 单页条数
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.HttpResult'
      summary: 搜索用户
      tags:
      - 用户相关接口
    post:
      description: 创建用户
      parameters:
      - description: 用户
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.HttpResult'
      summary: 创建用户
      tags:
      - 用户相关接口
    put:
      description: 更新用户
      parameters:
      - description: 用户
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.HttpResult'
      summary: 更新用户
      tags:
      - 用户相关接口
  /v1/user/{userid}:
    get:
      description: 获取用户
      parameters:
      - description: 用户ID
        in: path
        name: userid
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.HttpResult'
      summary: 获取用户
      tags:
      - 用户相关接口
  /v1/userinfo:
    get:
      description: 获取登录用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.HttpResult'
      summary: 获取登录用户信息
      tags:
      - 登录相关接口
  /v1/verify:
    get:
      description: 获取验证码
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.HttpResult'
      summary: 获取验证码
      tags:
      - 登录相关接口
swagger: "2.0"
